version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_database_dev
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/leap_careerwatch/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

  frontend:
    build:
      context: ./frontend
      args:
        - BUILD_COMMAND=start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/frontend # Add this line
      - /frontend/node_modules
    command: npm start # Add this line to start the react app
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  postgres_data:

